import danceStudioPaintingUrl from '../../assets/painting-dance-studio.png?url';
import draftingPaintingUrl from '../../assets/painting-drafting-table.png?url';
import fashionPaintingUrl from '../../assets/painting-fashion-house.png?url';
import fieldPaintingUrl from '../../assets/painting-green-field.png?url';
import musicStudioPaintingUrl from '../../assets/painting-music-studio.png?url';
import photoShootPaintingUrl from '../../assets/painting-photo-shoot.png?url';
import studioApartmentPaintingUrl from '../../assets/painting-studio-apartment.png?url';
import tvStudioPaintingUrl from '../../assets/painting-tv-studio.png?url';
import workbenchPaintingUrl from '../../assets/painting-workbench.png?url';

export const heroCopy = {
  title: 'One place for the work around WordPress',
  body: 'Spin up local sites, share previews, sync hosted work, automate the boring parts, and hand bigger tasks to agents without rebuilding your workflow every time.',
  primaryAction: 'Download for macOS',
  installCommand: 'npm install -g wp-studio@latest',
};

export const heroUseCases = [
  {
    id: 'local-site',
    label: 'Create local WordPress sites',
    title: 'Create local WordPress sites',
    body: 'Create a WordPress site on your machine with no Docker setup, open WP Admin, and start working against a disposable local environment.',
    start: 0,
    duration: 96,
    tilt: -5,
    crownLane: -1,
  },
  {
    id: 'blueprint',
    label: 'Reuse a project setup',
    title: 'Reuse a project setup',
    body: 'Use a Blueprint to recreate a preferred WordPress setup with the themes, plugins, settings, and starter content a project needs.',
    start: 0.063,
    duration: 96,
    tilt: 4,
    crownLane: 1,
  },
  {
    id: 'preview-link',
    label: 'Share a preview link',
    title: 'Share a preview link',
    body: 'Generate a temporary preview URL so teammates or clients can review your local WordPress site in a browser without pulling your project down.',
    start: 0.125,
    duration: 96,
    tilt: -2,
    crownLane: 0,
  },
  {
    id: 'sync-site',
    label: 'Push and pull hosted work',
    title: 'Push and pull hosted work',
    body: 'Connect a local site to WordPress.com hosting, then push or pull files and database changes when you are ready to move work between environments.',
    start: 0.188,
    duration: 96,
    tilt: 7,
    crownLane: -1,
  },
  {
    id: 'import-site',
    label: 'Bring a site into Studio',
    title: 'Bring a site into Studio',
    body: 'Bring a WordPress site into Studio from an archive, then test content, themes, plugins, and settings locally before making changes elsewhere.',
    start: 0.25,
    duration: 96,
    tilt: 3,
    crownLane: 1,
  },
  {
    id: 'export-site',
    label: 'Package a site to move',
    title: 'Package a site to move',
    body: 'Package a local Studio site into an archive that can be saved, shared, or moved into another WordPress workflow.',
    start: 0.313,
    duration: 96,
    tilt: -6,
    crownLane: 0,
  },
  {
    id: 'wp-cli',
    label: 'Automate with WP-CLI',
    title: 'Automate with WP-CLI',
    body: 'Use Studio CLI to list sites, open project paths, and run WP-CLI commands against a local WordPress site from the terminal.',
    start: 0.375,
    duration: 96,
    tilt: 6,
    crownLane: -1,
  },
  {
    id: 'studio-code',
    label: 'Open the project code',
    title: 'Open the project code',
    body: 'Jump from a Studio site into the matching code workspace so theme and plugin files are ready to edit in Studio Code.',
    start: 0.438,
    duration: 96,
    tilt: -4,
    crownLane: 1,
  },
  {
    id: 'assistant',
    label: 'Ask WordPress questions',
    title: 'Ask WordPress questions',
    body: 'Use the built-in Assistant to ask WordPress development questions while you work in the context of your Studio project.',
    start: 0.5,
    duration: 96,
    tilt: 2,
    crownLane: 0,
  },
  {
    id: 'debug-logs',
    label: 'Debug PHP errors',
    title: 'Debug PHP errors',
    body: 'Enable debugging, inspect logs, and keep the investigation tied to the local site that reproduced the issue.',
    start: 0.563,
    duration: 96,
    tilt: 5,
    crownLane: -1,
  },
  {
    id: 'database',
    label: 'Inspect WordPress tables',
    title: 'Inspect WordPress tables',
    body: 'Open a local database view when you need to inspect WordPress tables, verify content changes, or understand what a plugin stored.',
    start: 0.625,
    duration: 96,
    tilt: -3,
    crownLane: 1,
  },
  {
    id: 'xdebug',
    label: 'Step through PHP',
    title: 'Step through PHP',
    body: 'Connect a debugger to a Studio site so you can step through PHP execution instead of guessing where a theme or plugin goes wrong.',
    start: 0.688,
    duration: 96,
    tilt: 5,
    crownLane: 0,
  },
  {
    id: 'https',
    label: 'Test over local HTTPS',
    title: 'Test over local HTTPS',
    body: 'Use HTTPS locally when a feature, integration, or browser API expects a secure WordPress URL during development.',
    start: 0.75,
    duration: 96,
    tilt: -5,
    crownLane: -1,
  },
  {
    id: 'agent-skills',
    label: 'Give agents Studio context',
    title: 'Give agents Studio context',
    body: 'Add Studio-specific agent skills so AI coding tools can understand and operate on WordPress development tasks more effectively.',
    start: 0.813,
    duration: 96,
    tilt: 3,
    crownLane: 1,
  },
  {
    id: 'mcp',
    label: 'Let agents inspect local sites',
    title: 'Let agents inspect local sites',
    body: 'Expose Studio capabilities through MCP so compatible agents can inspect and work with local WordPress sites.',
    start: 0.875,
    duration: 96,
    tilt: -2,
    crownLane: 0,
  },
  {
    id: 'theme-plugin-work',
    label: 'Preview theme and plugin work',
    title: 'Preview theme and plugin work',
    body: 'Edit theme or plugin code against a live local WordPress site, then preview the exact behavior before syncing or sharing the work.',
    start: 0.938,
    duration: 96,
    tilt: 5,
    crownLane: -1,
  },
];

export const paintingOptions = [
  { id: 'drafting', label: 'Drafting', src: draftingPaintingUrl },
  { id: 'fashion', label: 'Fashion house', src: fashionPaintingUrl },
  { id: 'field', label: 'Field', src: fieldPaintingUrl },
  { id: 'music-studio', label: 'Music studio', src: musicStudioPaintingUrl },
  { id: 'dance-studio', label: 'Dance studio', src: danceStudioPaintingUrl },
  { id: 'photo-shoot', label: 'Photo shoot', src: photoShootPaintingUrl },
  { id: 'studio-apartment', label: 'Studio apartment', src: studioApartmentPaintingUrl },
  { id: 'tv-studio', label: 'TV studio', src: tvStudioPaintingUrl },
  { id: 'workbench', label: 'Workbench', src: workbenchPaintingUrl },
];
